#NOTE:
#This docker-compose file is only used currently for local testing of Prometheus and Grafana.
#It does not currently have any relation to the production version of the monitoring application.
#Run on Docker with `docker-compose up -d`

version: "3"

networks:
  grafana:

services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    volumes:
      - ./local-prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.external-url=/prometheus/"
      - "--web.route-prefix=/prometheus/"
    restart: unless-stopped
    ports:
      - 9090
    networks:
      - grafana

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    networks:
      - grafana
    volumes:
      - ./local-grafana/provisioning:/etc/grafana/provisioning
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=grafana"
      - "GF_SERVER_ROOT_URL=http://localhost/grafana"
      - "GF_SERVER_SERVE_FROM_SUB_PATH=true"

    ports:
      - 3000
  
  prom-pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    command:
      - "--web.external-url=/pushgateway/"
      - "--web.route-prefix=/pushgateway/"
    ports:
      - 9091
    networks:
      - grafana

  nginx-ingress:
    image: nginx:latest
    container_name: nginx-ingress
    hostname: ingress-monitoring
    volumes:
      - ./local-nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./local-nginx/index.html:/usr/share/nginx/html/index.html
      #NOTE: The local username is currently "admin" and the local password is "admin"
      #This username and password has been hashed and put into the local file at the  path below.
      #If you want to change these values, you can do so by re-hashing a username and password
      #with the apache2-utils package on Linux like this:
      #`apt-get install apache2-utils`
      #`htpasswd -c -b ./local-nginx/auth/.htpasswd my-username my-password
      - ./local-nginx/auth/.htpasswd:/etc/nginx/auth/.htpasswd
    ports:
      - 80:80
      - 443:443
    networks:
      - grafana